spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  application:
    name: ${SERVICE_NAME:user-service}
server:
  port: ${PORT:8080}
eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVER_URL:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
      

