spring:
  application:
    name: user-service  
  config:
    import: 'configserver:'
  cloud:
    config:
      uri: ${CONFIG_SERVICE_URL:http://localhost:8888}  
      label: ${CONFIG_LABEL:main}  
      profile: ${APP_PROFILE:default}  
server:
  port: ${PORT:8080}

